# Ce fichier parametrise les tests elementaires lances avant chaque commit
# Ces tests, appeles git hooks, lancent automatiquement des verifications
# sur votre code. Ainsi le code que vous "committez" est assure d'etre bien
# formate, avec des imports propres ...

repos:
  # Hooks in-built de pre-commit
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # Formattage du code
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: [--line-length=79]
  # Analyse qualite du code
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
  # # Tri des libraries
  # - repo: https://github.com/pycqa/isort
  #   rev: 5.12.0
  #   hooks:
  #     - id: isort
  #       name: isort (python)
  #       args: [--profile=black]
  # # Recherche de failles de securite
  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.5
  #   hooks:
  #     - id: bandit
